call schm_planificacion_comercial.sp_run_chek();
call schm_planificacion_comercial.sp_run_dap();
call schm_planificacion_comercial.sp_run_captaciones();
call schm_planificacion_comercial.sp_run_retail_credito();
call schm_planificacion_comercial.sp_run_retail_debito_chek();
call schm_planificacion_comercial.sp_run_saldos();
call schm_planificacion_comercial.sp_run_financiamiento();
call schm_planificacion_comercial.sp_run_leads_digitales();
call schm_planificacion_comercial.sp_metas_matinal();
call schm_planificacion_comercial.sp_metas_vespertino();
call schm_planificacion_comercial.sp_run_spos_tam();
call schm_planificacion_comercial.sp_run_tasa_plazo();
call schm_planificacion_comercial.sp_run_blandos_duros();
call schm_planificacion_comercial.sp_run_ref_rene();
call schm_planificacion_comercial.sp_run_ppff_canal();
call schm_planificacion_comercial.sp_run_ppff_resumen();
call schm_planificacion_comercial.sp_run_resumen();
call schm_planificacion_comercial.sp_run_clientes();

call schm_planificacion_comercial.sp_vis_blandos_duros();
call schm_planificacion_comercial.sp_vis_captaciones();
call schm_planificacion_comercial.sp_vis_clientes_con_saldo();
call schm_planificacion_comercial.sp_vis_clientes_con_uso();
call schm_planificacion_comercial.sp_vis_leads_digitales();
call schm_planificacion_comercial.sp_vis_productos_financieros();
call schm_planificacion_comercial.sp_vis_productos_financieros_canal();
call schm_planificacion_comercial.sp_vis_ref_mora();
call schm_planificacion_comercial.sp_vis_retail_credito();
call schm_planificacion_comercial.sp_vis_retail_debito_chek();
call schm_planificacion_comercial.sp_vis_saldos();
call schm_planificacion_comercial.sp_vis_tasa_plazo();
call schm_planificacion_comercial.sp_vis_financiamiento();
call schm_planificacion_comercial.sp_vis_spos_tam();
call schm_planificacion_comercial.sp_vis_spos_TOTALES();
call schm_planificacion_comercial.sp_vis_resumen_matinal();
call schm_planificacion_comercial.sp_vis_resumen_matinal_cierre();
call schm_planificacion_comercial.sp_vis_reusmen_vespertino();
call schm_planificacion_comercial.sp_vis_reusmen_vespertino_cierre();
call schm_planificacion_comercial.sp_vis_pagos();
call schm_planificacion_comercial.sp_vis_pagos_canal();

#email_sender = BigdataSesClient();
#email_sender.add_to('dvasquez@bancoripley.com,pmunozc@bancoripley.com');
#email_sender.add_subject('AWS MAIL AUTOMATICO: Calls del Matinal Terminados ');
#email_sender.add_text('Hola, SP Matinal ejecutado con éxito ');
#email_sender.add_text('\n \n');
#email_sender.add_text('v20240124');
#email_sender.add_text('\n \n');
#email_sender.add_text('Saludos Cordiales');
#email_sender.add_text('Equipo Arquitectura de Datos y Automatización');
#email_sender.add_text('Gerencia Data Analytics');
#email_sender.send_email();