/*==================================================================================================*/
/*==================================	EQUIPO DATOS Y PROCESOS		================================*/
/*==================================		DATA_MASTER			===================================*/
/* CONTROL DE VERSIONES
/* 2022-12-07 -- V12 -- SERGIO J.	--  SE AGREGAN NUEVOS CAMPOS PARA PLANES
/* 2022-11-24 -- V11 -- SERGIO J. 	-- SE AGREGA EL CAMPO SMS_CONSENT_STATUS
/* 2022-11-03 -- V10 -- DAVID V.	-- SE ACTUALIZAR EXPORT A AWS, SEGÚN NUEVAS DEFINICIONES A RAW.
/* 2022-10-03 -- V09 -- SERGIO J. 	--  ACTUALIZACIÓN DELETE AWS
/* 2022-09-22 -- V08 -- SERGIO J. 	--  SE AGREGAN LOS CAMPOS FECHA_LIMITE_PAGO Y FECHA_FACTURACION
/* 2022-09-13 -- V07 -- SERGIO J. 	-- SE AÑADE EXPORTACIÓN A AWS
/* 2022-07-20 -- V06 -- SERGIO J. 	-- SE AGREGAN CAMPOS FECHA_VENCIMIENTO_PUNTOS, PUNTOS_A_CADUCAR Y VIGENTE
/* 2021-08-12 -- V05 -- SERGIO J. 	-- SE ELIMINA SMS_CONSENT_STATUS
/* 2021-08-11 -- V04 -- SERGIO J. 	-- CAMPOS DINAMICOS PARA CAMPAÑAS
/* 2021-05-31 -- V03 -- SERGIO J. 	-- SE DESCOMENTA EL CAMPO SMS_CONSENT_STATUS
/* 2021-05-04 -- V02 -- SERGIO J. 	-- SE AGREGA EL COUNT DE LOS CAMPOS ENVIADOS EN EL CORREO
/* 2021-05-01 -- V01 -- SERGIO J. 	-- VERSIÓN ORIGINAL 

/* USUARIO QUE GENERA LA CAMPAÑA*/
%LET USUARIO = USER_BI;/* FECHA DE ACTUALIZACIÓN CON FORMATO MM/DD/YYYY*/
%LET TIEMPO_INICIO= %SYSFUNC(DATETIME()); /* INICIO DEL PROCESO DE CONTEO*/

PROC SQL;
CREATE TABLE UNICA_CARGA_DATA_MASTER (
APELLIDO CHAR(200),
DIRECCION CHAR(200),
EMAIL CHAR(200),
/* FECHA_CAPTACION CHAR(38),*/
/*FECHA_FACTURACION CHAR(2),*/
/*FECHA_LIMITE_PAGO CHAR(2),*/
ID_USUARIO NUMERIC(38),
NOMBRE CHAR(200),
NOMBRE_TC CHAR(200),
NUM_TC NUMERIC(12),
RETIRO_PLASTICO NUMERIC(12),
TELEFONO_MOVIL CHAR(38),
DIRECCION_NUM CHAR(38),
REGION CHAR(200),
COMUNA CHAR(200),
VAR_DM_NUM_1 NUMERIC(38),
VAR_DM_TXT_1 CHAR(38),
SEGMENTO CHAR(38),
SALDORPUNTOS1 CHAR(38),
FECHASALDO CHAR(38),
FECHA_VENCIMIENTO_PUNTOS CHAR(38),
PUNTOS_A_CADUCAR CHAR(38),
VIGENTE CHAR(1),
FINAL_PTOS_A NUMERIC(8),
PTOS_NVOS NUMERIC(8),
SEGMENTO_ANIO_ANTERIOR CHAR(11),
SEGMENTO_LOYALTY CHAR(11),
SEGMENTO_1 CHAR(11),
SEGMENTO_2 CHAR(11),
SEGMENTO_PLAN CHAR(11),
SEGMENTO_FINAL CHAR(11),
SI_TAM NUMERIC(1),
SI_CC NUMERIC(1),
SI_MC_CHEK NUMERIC(1),
SI_TD NUMERIC(1),
SI_TR NUMERIC(1),
SMS_CONSENT_STATUS CHAR(15))
;QUIT;

/* EJEMPLO DE INSERT DE DATOS DISPONIBLES PARA SER INSERTADOS EN TABLA “DATAMASTER_USER_TC” */
PROC SQL NOPRINT;
INSERT INTO UNICA_CARGA_DATA_MASTER (
APELLIDO,
DIRECCION,
EMAIL,
/*FECHA_FACTURACION,*/
/* FECHA_CAPTACION,*/
/*FECHA_LIMITE_PAGO,*/
ID_USUARIO,
NOMBRE,
NOMBRE_TC,
NUM_TC,
RETIRO_PLASTICO,
TELEFONO_MOVIL,
DIRECCION_NUM,
REGION,
COMUNA,
VAR_DM_NUM_1,
VAR_DM_TXT_1,
SEGMENTO,
SALDORPUNTOS1,
FECHASALDO,
FECHA_VENCIMIENTO_PUNTOS,
PUNTOS_A_CADUCAR,
VIGENTE,
FINAL_PTOS_A,
PTOS_NVOS,
SEGMENTO_ANIO_ANTERIOR,
SEGMENTO_LOYALTY,
SEGMENTO_1,
SEGMENTO_2,
SEGMENTO_PLAN,
SEGMENTO_FINAL,
SI_TAM,
SI_CC,
SI_MC_CHEK,
SI_TD,
SI_TR,
SMS_CONSENT_STATUS)

SELECT
APELLIDO,
DIRECCION,
EMAIL,
/*FECHA_FACTURACION,*/
/* "&FECHA.",*/
/*FECHA_LIMITE_PAGO,*/
ID_USUARIO,
NOMBRE,
"",
0,
0,
COMPRESS("569"||PUT(TELEFONO_MOVIL, BEST.)) AS TELEFONO_MOVIL,
DIRECCION_NUM,
REGION,
COMUNA,
0,
"",
SEGMENTO,
SALDORPUNTOS1,
FECHASALDO,
FECHA_VENCIMIENTO_PUNTOS,
PUNTOS_A_CADUCAR,
"1" AS VIGENTE,
FINAL_PTOS_A,
PTOS_NVOS,
SEGMENTO_ANIO_ANTERIOR,
SEGMENTO_LOYALTY,
SEGMENTO_1,
SEGMENTO_2,
SEGMENTO_PLAN,
SEGMENTO_FINAL,
SI_TAM,
SI_CC,
SI_MC_CHEK,
SI_TD,
SI_TR,
"OPTED-IN"
FROM PUBLICIN.BASE_DATA_MASTER
;QUIT;

/*==============================    EQUIPO ARQ. DATOS Y AUTOMATIZ.   ===============================*/
/*==============================        EXPORT_TO_AWS - INI          ===============================*/
/*%include"/sasdata/users_bi/resultados/oradiag_user_bi/aws/aws_delete_bulk.sas";*/
/*%delete_bulk(input_data_master,raw,oracloud,0);*/
/**/
/*%include"/sasdata/users_bi/resultados/oradiag_user_bi/aws/aws_export.sas";*/
/*%exportacion(input_data_master,unica_carga_data_master,raw,oracloud,0);*/

/*==============================        EXPORT_TO_AWS - END          ===============================*/
/*==============================    EQUIPO ARQ. DATOS Y AUTOMATIZ.   ===============================*/

/* EXPORT --> GENERACIÓN ARCHIVO CSV - DATA MASTER */
/*PROC EXPORT DATA = UNICA_CARGA_DATA_MASTER
OUTFILE="/sasdata/users94/user_bi/unica/input/INPUT-DataMaster_User_TC-&USUARIO..CSV"
DBMS=DLM REPLACE;
DELIMITER=",";
PUTNAMES=YES;
RUN;
*/

PROC SQL;
CREATE TABLE QUERY_DATA_MASTER AS 
   SELECT /* COUNT_OF_ID_USUARIO */
            (COUNT(T1.ID_USUARIO)) AS COUNT_OF_ID_USUARIO, 
          /* COUNT_OF_EMAIL */
            (COUNT(T1.EMAIL)) AS COUNT_OF_EMAIL, 
          /* COUNT_OF_TELEFONO_MOVIL */
            (COUNT(T1.TELEFONO_MOVIL)) AS COUNT_OF_TELEFONO_MOVIL
      FROM UNICA_CARGA_DATA_MASTER T1;
QUIT;

PROC SQL NOPRINT;
SELECT COUNT_OF_ID_USUARIO AS COUNT_ID_USUARIO INTO:COUNT_ID_USUARIO
FROM QUERY_DATA_MASTER;
SELECT COUNT_OF_EMAIL AS COUNT_EMAIL INTO:COUNT_EMAIL
FROM QUERY_DATA_MASTER;
SELECT COUNT_OF_TELEFONO_MOVIL AS COUNT_TELEFONO_MOVIL INTO:COUNT_TELEFONO_MOVIL
FROM QUERY_DATA_MASTER;
;QUIT;

/*SALIDA DEL PROCESO INDICANDO EL TIEMPO TOTAL */
DATA _NULL_;
FGENERA = COMPRESS(INPUT(PUT(TODAY(),MMDDYY.),$10.),"-",);
CALL SYMPUT("FECHADIA",FGENERA);
RUN;
%PUT &FECHADIA;

/*==================================	EMAIL CON CASILLA VARIABLE	================================*/
PROC SQL NOPRINT;                              
	SELECT EMAIL INTO :EDP_BI FROM RESULT.EDP_BI_DESTINATARIOS WHERE CODIGO = EDP_BI;
	SELECT EMAIL INTO :DEST_1 FROM RESULT.EDP_BI_DESTINATARIOS WHERE CODIGO = JEFE_ARQ_DAT;
	SELECT EMAIL INTO :DEST_2 FROM RESULT.EDP_BI_DESTINATARIOS WHERE CODIGO = PM_ARQ_DAT_1;
QUIT;
%PUT &=EDP_BI;	%PUT &=DEST_1;	%PUT &=DEST_2;

DATA _NULL_;
FILENAME OUTBOX EMAIL
FROM 	= ("&EDP_BI")
TO 		= ("&DEST_2","&DEST_1")
SUBJECT = ("MAIL_AUTOM: - PROCESO DATA_MASTER");
FILE OUTBOX;
 	PUT "DATA MASTER";
 	PUT "    PROCESO DATA_MASTER, EJECUTADO CON FECHA: &FECHADIA.";  
 	PUT ; 
 	PUT "	FECHA: &FECHADIA."; 
 	PUT "	COUNT_ID_USUARIO: &COUNT_ID_USUARIO.";
 	PUT "	COUNT_EMAIL: &COUNT_EMAIL.";
 	PUT "	COUNT_TELEFONO_MOVIL: &COUNT_TELEFONO_MOVIL.";
 	PUT ;
 	PUT ;
 	PUT PROCESO VERS. 12; 
 	PUT;
 	PUT;
 	PUT ATTE.;
 	PUT EQUIPO ARQUITECTURA DE DATOS Y AUTOMATIZACIÓN BI;
 	PUT;
RUN;
FILENAME OUTBOX CLEAR;

/* UTILIZACIÓN VARIABLE TIEMPO / CUANTO SE DEMORÓ */
DATA _NULL_;
DUR = DATETIME() - &TIEMPO_INICIO;
PUT 30*- /  DURACIÓN TOTAL: DUR TIME13.2 / 30*-;
RUN;
